<?php require_once dirname(__FILE__).'/itemclass-list.phtml' ?>
<?php require_once dirname(__FILE__).'/itemclass-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/itemclass-accountgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/itemclass-accountform.phtml' ?>
<?php require_once dirname(__FILE__).'/itemclass-filesgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/itemclass-filesform.phtml' ?>



