<div id="pnl_editbilloutgrid">
	<div class="fgta-page-title">Daftar Bill</div>
	<div id="pnl_editbilloutgrid-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>

	<!--// Untuk keperluan search di detil
	<div id="pnl_editbilloutgrid-pnl_head" style="display: flex; align-items: flex-end">
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-item" style="width: 50px;">Cari</div>
			<div class="list-search-item">
				<input id="pnl_editbilloutgrid-txt_search" class="easyui-textbox" style="width: 100%">
			</div>
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_editbilloutgrid-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>
		</div>
	</div>	
	//-->

	<div style="margin-top: 10px; margin-bottom: 15px">
		<table id="pnl_editbilloutgrid-tbl_list" paging="true" cellspacing="0" width="100%" class="deftable">
			<thead>
				<tr>
					<th type="check">chk</th>					
					<th mapping="colltargetbillout_datetarget">colltargetbillout_datetarget</th>
					<th mapping="partner_name">partner_name</th>
					<th mapping="billout_ref">billout_ref</th>
					<th mapping="billout_descr">billout_descr</th>
					<th mapping="billout_idrnett" style="text-align: right" formatter="row_format_number">billout_idrnett</th>
					<th mapping="billout_ppnval" style="text-align: right" formatter="row_format_number">billout_ppnval</th>
					<th mapping="billout_pphval" style="text-align: right" formatter="row_format_number">billout_pphval</th>
					<th mapping="billout_discp" style="text-align: right" formatter="row_format_number">billout_discp</th>
					<th mapping="billout_discval" style="text-align: right" formatter="row_format_number">billout_discval</th>
					<th mapping="billout_idrtopay" style="text-align: right" formatter="row_format_number">billout_idrtopay</th>
					<th mapping="billout_ppntopay" style="text-align: right" formatter="row_format_number">billout_ppntopay</th>
					<th mapping="billout_totalpayment" style="text-align: right" formatter="row_format_number">billout_totalpayment</th>
				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 30px; border-bottom: 1px solid #000000; text-align: center">*</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Payment Date</td>
					<td class="fgtable-head" style="width: 200px; border-bottom: 1px solid #000000">Partner</td>
					<td class="fgtable-head" style="width: 200px; border-bottom: 1px solid #000000">No Ivoice</td>
					<td class="fgtable-head" style="border-bottom: 1px solid #000000">Descr</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Nett</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">PPN</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">PPh</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Disc (%)</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Discount</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Payment</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Payment PPN</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Total Payment</td>
				</tr>
			</thead>
			<tfoot>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-foot" style="width: 30px; border-bottom: 1px solid #000000; text-align: center">*</td>
					<td class="fgtable-foot" style="border-bottom: 1px solid #000000">&nbsp;</td>
					<td class="fgtable-foot" style="border-bottom: 1px solid #000000">&nbsp;</td>
					<td class="fgtable-foot" style="border-bottom: 1px solid #000000">&nbsp;</td>
					<td id="pnl_editbilloutgrid-totalnett" class="fgtable-foot" style="font-weight: bold; text-align: right; border-bottom: 1px solid #000000">0</td>
					<td id="pnl_editbilloutgrid-totalppn" class="fgtable-foot" style="font-weight: bold; text-align: right; border-bottom: 1px solid #000000">0</td>
					<td id="pnl_editbilloutgrid-totalpph" class="fgtable-foot" style="font-weight: bold; text-align: right; border-bottom: 1px solid #000000">0</td>
					<td id="pnl_editbilloutgrid-totaldisc" class="fgtable-foot" style="font-weight: bold; text-align: right; border-bottom: 1px solid #000000"></td>
					<td id="pnl_editbilloutgrid-totaldiscval" class="fgtable-foot" style="font-weight: bold; text-align: right; border-bottom: 1px solid #000000">0</td>
					<td id="pnl_editbilloutgrid-totalidrtopay" class="fgtable-foot" style="font-weight: bold; text-align: right; border-bottom: 1px solid #000000">0</td>
					<td id="pnl_editbilloutgrid-totalppntopay" class="fgtable-foot" style="font-weight: bold; text-align: right; border-bottom: 1px solid #000000">0</td>
					<td id="pnl_editbilloutgrid-totalpayment" class="fgtable-foot" style="font-weight: bold; text-align: right; border-bottom: 1px solid #000000">0</td>
				</tr>
			</tfoot>
		</table>
	</div>

	<div id="pnl_editbilloutgrid-control">
		<div  style="display: flex; justify-content: space-between; margin-bottom: 40px">
			<div>
				<a id="pnl_editbilloutgrid-removechecked" href="javascript:void(0)" class="easyui-linkbutton c8">Hapus Checked</a>
				<a id="pnl_editbilloutgrid-modifychecked" href="javascript:void(0)" class="easyui-linkbutton c8">Modify Checked</a>
			</div>

			<div>
				<a href="javascript:void(0)" class="pnl_edititemsgrid-addrow-multi easyui-linkbutton c8">Tambah Baris</a>
				<a id="pnl_editbilloutgrid-addrow" href="javascript:void(0)" class="easyui-linkbutton c8">Tambah Unbill</a>
			</div>

			<div>
			</div>
		</div>


		<div id="pnl_editbilloutgrid-modify" style="margin-bottom: 100px">
			<form id="pnl_editbilloutgrid-form">

			<div class="form_row" >
				<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Total Row</div>
				<div class="form_input_col" style="border: 0px solid black" id="pnl_editbilloutgrid-modifyrowcount"></div>
			</div>

			<div class="form_row" >
				<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Total Payment</div>
				<div class="form_input_col" style="border: 0px solid black" id="pnl_editbilloutgrid-modifyrowtotalpay"></div>
			</div>

			<div class="form_row" >
				<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Payment Date</div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_editbilloutgrid-dt_colltargetbillout_datetarget" class="easyui-datebox" style="width: 400px" mapping="colltargetbillout_datetarget" data-options="editable:false ">
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
			</div>

			<div class="form_row" >
				<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Discount (%)</div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_editbilloutgrid-txt_billout_discp" class="easyui-numberbox" mapping="billout_discp" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  ">
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
			</div>
			</form>

			<div class="form_row" style="margin-top: 30px">
				<div class="form_label_col"></div>
				<div class="form_input_col" style="border: 0px solid black">
					<a id="pnl_editbilloutgrid-btn_apply" class="easyui-linkbutton c1" style="width: 100px">Apply</a>
					<a id="pnl_editbilloutgrid-btn_cancel" class="easyui-linkbutton" style="width: 100px">Cancel</a>
				</div>
			</div>

		</div>

	</div>


	<div id="pnl_editbilloutgrid-error"></div>

</div>	
