<div id="pnl_editbilloutgrid">
	<div class="fgta-page-title">Daftar Bill</div>
	<div id="pnl_editbilloutgrid-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>

	<!--// Untuk keperluan search di detil
	<div id="pnl_editbilloutgrid-pnl_head" style="display: flex; align-items: flex-end">
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-item" style="width: 50px;">Cari</div>
			<div class="list-search-item">
				<input id="pnl_editbilloutgrid-txt_search" class="easyui-textbox" style="width: 100%">
			</div>
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_editbilloutgrid-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>
		</div>
	</div>	
	//-->

	<div style="margin-top: 10px; margin-bottom: 15px">
		<table id="pnl_editbilloutgrid-tbl_list" paging="true" cellspacing="0" width="100%" class="deftable">
			<thead>
				<?php
				$customview = __DIR__.'/colltarget-billoutgrid-customview.phtml'; 
				if (is_file($customview)) {
					include $customview;
				} else { ?>
				<tr>
<th type="check">chk</th>					
					<th mapping="colltargetbillout_id">colltargetbillout_id</th>
					<th mapping="partner_name">partner_name</th>
					<th mapping="billout_descr">billout_descr</th>
					<th mapping="colltargetbillout_datetarget">colltargetbillout_datetarget</th>
					<th mapping="billout_idr" style="text-align: right" formatter="row_format_number">billout_idr</th>
					<th mapping="billout_idrtopay" style="text-align: right" formatter="row_format_number">billout_idrtopay</th>
					<th mapping="billout_ppntopay" style="text-align: right" formatter="row_format_number">billout_ppntopay</th>
					<th mapping="billout_idrtotal" style="text-align: right" formatter="row_format_number">billout_idrtotal</th>

					<th mapping=""></th>
				</tr>
				<tr style="background-color: #cccccc; height: 30px">
<td class="fgtable-head" style="width: 30px; border-bottom: 1px solid #000000; text-align: center">*</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Partner</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Tagihan</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Target Date</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Outstanding Payment</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Payment</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Payment PPN</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Subtotal Target</td>

					<td class="fgtable-head" style="border-bottom: 1px solid #000000; text-align: center">&nbsp;</td>
				</tr>
				<?php } ?>
			</thead>
		</table>
	</div>

	<div id="pnl_editbilloutgrid-control" style="display: flex; justify-content: space-between; margin-bottom: 100px">
		<div>
			<a id="pnl_editbilloutgrid-removechecked" href="javascript:void(0)" class="easyui-linkbutton c8">Hapus Checked</a>
		</div>

		<div>
			<a id="pnl_editbilloutgrid-addrow" href="javascript:void(0)" class="easyui-linkbutton c8">Tambah Baris</a>
		</div>

		<div>
		</div>

	</div>


</div>	
