<?php

	$doc_iso_reg = "<yout form iso number>";
	$report_title['id'] = "AGING AP";
	$report_title['en'] = "dddd";

	$report_printid = strtoupper(uniqid());
	$report_printdate = date('d/m/Y');
	$report_date = $this->report_date;

	$doc_descr = "per tanggal $report_printdate";
?>



<div id="wrapper" style="z-index: 10">

	<!-- page header: selalu ditampilkan pada tiap halaman, kecuali halaman 1 -->
	<div id="pageheader" class="fullwidth">
		<div>
			<div><?=$report_title['id']?></div>
			<div style="font-style: italic"><?=$doc_descr?></div>
		</div>
		<div style="text-align: right; width: 70mm;">
			<div style="display:inline-block; width: 38mm;"><b>Print Id</b> <?=$report_printid?></div>
			<div style="display:inline-block; width: 30mm;">&nbsp;</div>
			
		</div>
	</div>


	<!-- report header --->
	<div id="reporttitle" class="fullwidth">
		<div style="display: flex; justify-content: space-between">

			<div >
				<div style="font-weight: bold; font-size: 12pt; "><?=__COMPANY_NAME__?></div>
				<div style="font-weight: bold; font-size: 12pt; margin-top: 2mm"><?=$report_title['id']?></div>
			</div>	
			<div style="text-align: right">
				<!-- <img id="ellogo" src="index.php/public/assets/logo-printform-right.svg"> -->
			</div>			
		</div>
	</div>

	<div class="fullwidth" style="position: relative; margin-top: 2mm; ">
		<div style="display: flex; justify-content: space-between">
			<div style="font-size: 8pt;"><b>per tanggal</b> <?=$report_date?></div>
			<!-- <div style="font-size: 8pt;"><b>Page</b> 1 <b>of</b> <span id="reporttotalpage">1</span></div> -->
		</div>
	</div>


	<!-- report content -->
	<div id="reportcontent" class="fullwidth">
		<?php $i=0?>
		<table id="obj_reporttable" width="100%" cellpadding="0" cellspacing="0" data-cols-width="10,20,60,30,30,30,30">
			<thead>
				<?php PrintTableHeader()?>
			</thead>
			<tbody>
				<?php
				$TOTAL = [
					'age_0' => 0,
					'age_30' => 0,
					'age_60' => 0,
					'age_90' => 0,
					'age_120' => 0,
					'outstanding_idr' => 0,
				];

				$SUBTOTAL = [
					'age_0' => 0,
					'age_30' => 0,
					'age_60' => 0,
					'age_90' => 0,
					'age_120' => 0,
					'outstanding_idr' => 0,
				];

				$last_partner_name = "";

				$rownumber=0;
				foreach ($this->rows as $row) { 
					if ($row['partner_name']!=$last_partner_name) {
						if ($i>0) {
							PrintGroupFooter($SUBTOTAL);
							$this->ArayValueReset($SUBTOTAL);
							$rownumber = 0;
						}
						PrintGroupHeader($row);
					}
					$i++;
					$rownumber++;
					PrintRow($row, $rownumber);
					$this->ArrayValueAdd($TOTAL, $row);
					$this->ArrayValueAdd($SUBTOTAL, $row);
					$last_partner_name = $row['partner_name'];
				}
				if ($i>0) { PrintGroupFooter($SUBTOTAL); }
				?>
				
			</tbody>
			<tfoot>
				<?php PrintTableFooter($TOTAL) ?>
			</tfoot>			
		</table>
		<script>global.totalrowcount = '<?=($i-1)?>'</script>
	</div>


</div>

<div id="wrapperfooter" class="fullwidth" style="z-index: 20">
	<div id="reportfooter" style="display: flex; justify-content: space-between; height: 10mm; ">
		&nbsp;
	<div>				
</div>






<?php function PrintTableHeader() { ?>
	<!-- <tr>
		<th class="rowhead ptdata-col-no" data-fill-color='CCCCCC'>No</th>
		<th class="rowhead rptdata-col-coacode" data-fill-color='CCCCCC'>ID</th>
		<th class="rowhead rptdata-col-coaname" data-fill-color='CCCCCC'>Nama</th>
		<th class="rowhead rptdata-col-val" data-fill-color='CCCCCC'>Not Yet Due</th>
		<th class="rowhead rptdata-col-val" data-fill-color='CCCCCC'>0 s/d 30</th>
		<th class="rowhead rptdata-col-val" data-fill-color='CCCCCC'>31 s/d 60</th>
		<th class="rowhead rptdata-col-val" data-fill-color='CCCCCC'>61 s/d 90</th>
		<th class="rowhead rptdata-col-val" data-fill-color='CCCCCC'>> 90</th>
		<th class="rowhead rptdata-col-val" data-fill-color='CCCCCC'>TOTAL</th>
	</tr> -->
	<tr>
		<td></td>
	</tr>
<?php } ?>	


<?php function PrintGroupHeader($row) { ?>
	<tr>
		<td class="" style="vertical-align:top; font-weight: bold; padding-top: 20px; padding-bottom: 5px" colspan="9"><?=$row['partner_name']?></td>
	</tr>
	<tr>
		<td class="grouphead" style="vertical-align:top; text-align: center" data-fill-color='CCCCCC'>No</td>
		<td class="grouphead" style="vertical-align:top; " data-fill-color='CCCCCC'>Ref</td>
		<td class="grouphead" style="vertical-align:top; " data-fill-color='CCCCCC'>Descr</td>
		<td class="grouphead rptdata-col-val" data-t="n" data-fill-color='CCCCCC'>Current</td>
		<td class="grouphead rptdata-col-val" data-t="n" data-fill-color='CCCCCC'>0 - 30</td>
		<td class="grouphead rptdata-col-val" data-t="n" data-fill-color='CCCCCC'>31 - 60</td>
		<td class="grouphead rptdata-col-val" data-t="n" data-fill-color='CCCCCC'>61 - 90</td>
		<td class="grouphead rptdata-col-val" data-t="n" data-fill-color='CCCCCC'>> 90</td>
		<td class="grouphead rptdata-col-val" data-t="n" data-fill-color='CCCCCC'>Total</td>
	</tr>
<?php } ?>


<?php function PrintRow($row, $rownumber=0) { ?>
	<tr>
		<td class="itemrow" style="vertical-align:top; text-align: center" data-fill-color='CCCCCC'><?=$rownumber?></td>
		<td class="itemrow" style="vertical-align:top; " data-fill-color='CCCCCC'><?=$row['jurnal_id']?></td>
		<td class="itemrow" style="vertical-align:top; " data-fill-color='CCCCCC'><?=$row['jurnal_descr']?></td>
		<td class="itemrow rptdata-col-val" data-t="n" data-num-fmt="#,##0" data-fill-color='CCCCCC'><?=number_format($row['age_0'])?></td>
		<td class="itemrow rptdata-col-val" data-t="n" data-num-fmt="#,##0" data-fill-color='CCCCCC'><?=number_format($row['age_30'])?></td>
		<td class="itemrow rptdata-col-val" data-t="n" data-num-fmt="#,##0" data-fill-color='CCCCCC'><?=number_format($row['age_60'])?></td>
		<td class="itemrow rptdata-col-val" data-t="n" data-num-fmt="#,##0" data-fill-color='CCCCCC'><?=number_format($row['age_90'])?></td>
		<td class="itemrow rptdata-col-val" data-t="n" data-num-fmt="#,##0" data-fill-color='CCCCCC'><?=number_format($row['age_120'])?></td>
		<td class="itemrow rptdata-col-val" data-t="n" data-num-fmt="#,##0" data-fill-color='CCCCCC'><?=number_format($row['outstanding_idr'])?></td>
	</tr>
<?php } ?>


<?php function PrintGroupFooter($SUBTOTAL, $args=null) { ?>
	<tr>
		<td class="groupfoot" style="vertical-align:top;" colspan="3" data-fill-color='CCCCCC'>Subtotal</td>
		<td class="groupfoot rptdata-col-val" data-t="n" data-num-fmt="#,##0" data-fill-color='CCCCCC'><?=number_format($SUBTOTAL['age_0'])?></td>
		<td class="groupfoot rptdata-col-val" data-t="n" data-num-fmt="#,##0" data-fill-color='CCCCCC'><?=number_format($SUBTOTAL['age_30'])?></td>
		<td class="groupfoot rptdata-col-val" data-t="n" data-num-fmt="#,##0" data-fill-color='CCCCCC'><?=number_format($SUBTOTAL['age_60'])?></td>
		<td class="groupfoot rptdata-col-val" data-t="n" data-num-fmt="#,##0" data-fill-color='CCCCCC'><?=number_format($SUBTOTAL['age_90'])?></td>
		<td class="groupfoot rptdata-col-val" data-t="n" data-num-fmt="#,##0" data-fill-color='CCCCCC'><?=number_format($SUBTOTAL['age_120'])?></td>
		<td class="groupfoot rptdata-col-val" data-t="n" data-num-fmt="#,##0" data-fill-color='CCCCCC'><?=number_format($SUBTOTAL['outstanding_idr'])?></td>
	</tr>
<?php } ?>

<?php function PrintTableFooter($TOTAL, $args=null) { ?>
	<tr>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td class="tablefoot" style="vertical-align:top;" colspan="3" data-fill-color='CCCCCC'>TOTAL</td>
		<td class="tablefoot rptdata-col-val" data-t="n" data-num-fmt="#,##0" data-fill-color='CCCCCC'><?=number_format($TOTAL['age_0'])?></td>
		<td class="tablefoot rptdata-col-val" data-t="n" data-num-fmt="#,##0" data-fill-color='CCCCCC'><?=number_format($TOTAL['age_30'])?></td>
		<td class="tablefoot rptdata-col-val" data-t="n" data-num-fmt="#,##0" data-fill-color='CCCCCC'><?=number_format($TOTAL['age_60'])?></td>
		<td class="tablefoot rptdata-col-val" data-t="n" data-num-fmt="#,##0" data-fill-color='CCCCCC'><?=number_format($TOTAL['age_90'])?></td>
		<td class="tablefoot rptdata-col-val" data-t="n" data-num-fmt="#,##0" data-fill-color='CCCCCC'><?=number_format($TOTAL['age_120'])?></td>
		<td class="tablefoot rptdata-col-val" data-t="n" data-num-fmt="#,##0" data-fill-color='CCCCCC'><?=number_format($TOTAL['outstanding_idr'])?></td>
	</tr>
<?php } ?>
