<?php

	$doc_iso_reg = "<yout form iso number>";
	$report_title['id'] = "AGING AP";
	$report_title['en'] = $this->partner_name;

	$report_printid = strtoupper(uniqid());
	$report_printdate = date('d/m/Y');
	$report_date = $this->report_date;

	$doc_descr = "per tanggal $report_printdate";
?>



<!-- <div style="position: absolute; z-index: -100">
	<div  id="pagemeasure">&nbsp;</div>
</div> -->


<div id="wrapper" style="z-index: 10">

	<!-- page header: selalu ditampilkan pada tiap halaman, kecuali halaman 1 -->
	<div id="pageheader" class="fullwidth">
		<div>
			<div><?=$report_title['id']?></div>
			<div style="font-style: italic"><?=$doc_descr?></div>
		</div>
		<div style="text-align: right; width: 70mm;">
			<div style="display:inline-block; width: 38mm;"><b>Print Id</b> <?=$report_printid?></div>
			<div style="display:inline-block; width: 30mm;">&nbsp;</div>
			
		</div>
	</div>


	<!-- report header --->
	<div id="reporttitle" class="fullwidth">
		<div style="display: flex; justify-content: space-between">

			<div >
				<div style="font-size: 7pt; font-style: italic"><?=$doc_iso_reg?></div>
				<div style="font-weight: bold; font-size: 12pt; margin-top: 2mm"><?=$report_title['id']?></div>
				<div style="font-weight: bold; font-style: italic; font-size: 10pt; color: #666"><?=$report_title['en']?></div>
			</div>	
			<div style="text-align: right">
				<img id="ellogo" src="index.php/public/assets/logo-printform-right.svg">
			</div>			
		</div>
	</div>


	<div class="fullwidth" style="position: relative; margin-top: 2mm; ">
		<div style="font-size: 8pt;">
			<b>per tanggal</b> <?=$report_date?>
		</div>
		<div style="display: flex; justify-content: space-between; margin-top: 2mm">
			<div style="font-size: 8pt;"><b>Page</b> 1 <b>of</b> <span id="reporttotalpage">1</span></div>
			<div style="text-align: right; font-size: 8pt"><b>Print Id</b> <?=$report_printid?></div>
		</div>
	</div>


	<!-- report content -->
	<div id="reportcontent" class="fullwidth">
		<table id="obj_reporttable" width="100%" data-cols-width="10,20,60,30,30,30,30">
			<thead>
				<tr>
					<th class="rowhead ptdata-col-no" data-fill-color='CCCCCC'>No</th>
					<th class="rowhead rptdata-col-coacode" data-fill-color='CCCCCC'>ID</th>
					<th class="rowhead rptdata-col-coacode" data-fill-color='CCCCCC'>Date</th>
					<th class="rowhead rptdata-col-coacode" data-fill-color='CCCCCC'>Age</th>
					<th class="rowhead rptdata-col-val" data-fill-color='CCCCCC'>Not Yet Due</th>
					<th class="rowhead rptdata-col-val" data-fill-color='CCCCCC'>0 s/d 30</th>
					<th class="rowhead rptdata-col-val" data-fill-color='CCCCCC'>31 s/d 60</th>
					<th class="rowhead rptdata-col-val" data-fill-color='CCCCCC'>61 s/d 90</th>
					<th class="rowhead rptdata-col-val" data-fill-color='CCCCCC'>> 90</th>
					<th class="rowhead rptdata-col-val" data-fill-color='CCCCCC'>TOTAL</th>
				</tr>
			</thead>
			<tbody>
				<!-- 45 -->
				<?php 
				$i=0;
				$total_value = 0;
				$total_notyetdue = 0;
				$total_due_030 = 0;
				$total_due_060 = 0;
				$total_due_090 = 0;
				$total_due_more = 0;

				foreach ($this->rows as $row) { 
					$i++;

				
					$total_value += $row['value'];
					$total_notyetdue += $row['notyetdue'];
					$total_due_030 += $row['due_030'];
					$total_due_060 += $row['due_060'];
					$total_due_090 += $row['due_090'];
					$total_due_more += $row['due_more'];
				?>
				<tr>
					<td class="row rptdata-col-no"><?=$i?></td>
					<td class="row rptdata-col-coacode"><?=$row['jurnal_id']?></td>
					<td class="row rptdata-col-coacode"><?=$row['jurnal_duedate']?></td>
					<td class="row rptdata-col-coacode"><?=$row['age']?></td>
					<td class="row rptdata-col-val" data-t="n" data-num-fmt="#,##0"><?=number_format($row['notyetdue'])?></td>
					<td class="row rptdata-col-val" data-t="n" data-num-fmt="#,##0"><?=number_format($row['due_030'])?></td>
					<td class="row rptdata-col-val" data-t="n" data-num-fmt="#,##0"><?=number_format($row['due_060'])?></td>
					<td class="row rptdata-col-val" data-t="n" data-num-fmt="#,##0"><?=number_format($row['due_090'])?></td>
					<td class="row rptdata-col-val" data-t="n" data-num-fmt="#,##0"><?=number_format($row['due_more'])?></td>
					<td class="row rptdata-col-val" data-t="n" data-num-fmt="#,##0"><?=number_format($row['value'])?></td>
				</tr>
				<?php } ?>

				<tr>
					<td class="rowfoot" colspan="4" style="text-align: center" data-fill-color='CCCCCC'>TOTAL</td>
					<td class="rowfoot rptdata-col-val" data-t="n" data-num-fmt="#,##0" data-fill-color='CCCCCC'><?=number_format($total_notyetdue)?></td>
					<td class="rowfoot rptdata-col-val" data-t="n" data-num-fmt="#,##0" data-fill-color='CCCCCC'><?=number_format($total_due_030)?></td>
					<td class="rowfoot rptdata-col-val" data-t="n" data-num-fmt="#,##0" data-fill-color='CCCCCC'><?=number_format($total_due_060)?></td>
					<td class="rowfoot rptdata-col-val" data-t="n" data-num-fmt="#,##0" data-fill-color='CCCCCC'><?=number_format($total_due_090)?></td>
					<td class="rowfoot rptdata-col-val" data-t="n" data-num-fmt="#,##0" data-fill-color='CCCCCC'><?=number_format($total_due_more)?></td>
					<td class="rowfoot rptdata-col-val" data-t="n" data-num-fmt="#,##0" data-fill-color='CCCCCC'><?=number_format($total_value)?></td>
				</tr>				
			</tbody>
			<tfoot>
			</tfoot>			
		</table>
		<script>global.totalrowcount = '<?=($i-1)?>'</script>
	</div>


</div>

<div id="wrapperfooter" class="fullwidth" style="z-index: 20">
	<div id="reportfooter" style="display: flex; justify-content: space-between; height: 10mm; ">
		&nbsp;
	<div>				
</div>