<div id="pnl_editaccbudgetgrid">
	<div class="fgta-page-title">Daftar Detil</div>
	<div id="pnl_editaccbudgetgrid-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>

	<!--// Untuk keperluan search di detil
	<div id="pnl_editaccbudgetgrid-pnl_head" style="display: flex; align-items: flex-end">
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-item" style="width: 50px;">Cari</div>
			<div class="list-search-item">
				<input id="pnl_editaccbudgetgrid-txt_search" class="easyui-textbox" style="width: 100%">
			</div>
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_editaccbudgetgrid-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>
		</div>
	</div>	
	//-->

	<div class="pnl_editaccbudgetgrid-control" style="display: flex; justify-content: space-between;">
		<div>
			<a href="javascript:void(0)" class="pnl_editaccbudgetgrid-removechecked easyui-linkbutton c8">Hapus Checked</a>
		</div>
		<div>
			<a href="javascript:void(0)" class="pnl_editaccbudgetgrid-addrow easyui-linkbutton c8">Tambah Baris</a>
			<a href="javascript:void(0)" class="pnl_editaccbudgetgrid-addrow-multi easyui-linkbutton c8">Tambah Baris Multi</a>
		</div>
		<div>
		</div>
	</div>


	<div style="margin-top: 10px; margin-bottom: 15px">
		<table id="pnl_editaccbudgetgrid-tbl_list" paging="true" cellspacing="0" width="100%" class="deftable">
			<thead>
				<tr>
					<th type="check">chk</th>					
					<th mapping="deptbudgetacc_id">deptbudgetacc_id</th>
					<th mapping="accbudget_name">accbudget_name</th>
					<th mapping="accbudget_nameshort">accbudget_nameshort</th>

					<th mapping=""></th>
				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 30px; border-bottom: 1px solid #000000; text-align: center">*</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Account</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Nama Pendek</td>

					<td class="fgtable-head" style="border-bottom: 1px solid #000000; text-align: center">&nbsp;</td>
				</tr>
			</thead>
		</table>
	</div>

	<div class="pnl_editaccbudgetgrid-control" style="display: flex; justify-content: space-between; margin-bottom: 100px">
		<div>
			<a href="javascript:void(0)" class="pnl_editaccbudgetgrid-removechecked easyui-linkbutton c8">Hapus Checked</a>
		</div>

		<div>
			<a href="javascript:void(0)" class="pnl_editaccbudgetgrid-addrow easyui-linkbutton c8">Tambah Baris</a>
			<a href="javascript:void(0)" class="pnl_editaccbudgetgrid-addrow-multi easyui-linkbutton c8">Tambah Baris Multi</a>
		</div>

		<div>
		</div>
	</div>


</div>	
