<div id="pnl_editinvitedform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Invited</div>
		<a id="pnl_editinvitedform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_editinvitedform-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>


	<form id="pnl_editinvitedform-form">

		<div class="form_row">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editinvitedform-txt_crmeventinvited_id" class="easyui-textbox" mapping="crmeventinvited_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Contact</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editinvitedform-txt_crmeventinvited_contact" class="easyui-textbox" mapping="crmeventinvited_contact" uppercase="true" maxlength="90"  style="width: 400px" data-options="multiline:false , required: true, invalidMessage: 'Contact harus diisi dengan no telpon / email' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;">Nomor/email yang akan di hubungi</div>
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editinvitedform-txt_crmeventinvited_name" class="easyui-textbox" mapping="crmeventinvited_name" uppercase="true" maxlength="90"  style="width: 400px" data-options="multiline:false , required: true, invalidMessage: 'Nama harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editinvitedform-txt_crmeventinvited_address" class="easyui-textbox" mapping="crmeventinvited_address" uppercase="true" maxlength="255"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">City</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editinvitedform-txt_crmeventinvited_city" class="easyui-textbox" mapping="crmeventinvited_city" uppercase="true" maxlength="30"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editinvitedform-chk_crmeventinvited_iscontacted" class="easyui-checkbox c1" mapping="crmeventinvited_iscontacted" data-options="label: 'Contacted', labelPosition: 'after', disabled:false, checked: false , readonly: true">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Contact Date</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editinvitedform-dt_crmeventinvited_contactdate" class="easyui-datebox" style="width: 400px" mapping="crmeventinvited_contactdate" data-options="editable:false , readonly: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col easyui-tooltip" title="yang bertugas menhubungi kontak ini" style="border: 0px solid black; vertical-align: top; margin-top: 7px;">PIC</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editinvitedform-cbo_user_id" class="easyui-combo" style="width: 400px" mapping="user_id" display="user_fullname" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'PIC harus diisi', prompt: '-- PILIH --'">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Event</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editinvitedform-txt_crmevent_id" class="easyui-textbox" mapping="crmevent_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_editinvitedform-autoadd" type="checkbox"><label for="pnl_editinvitedform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_editinvitedform-btn_save" class="easyui-linkbutton c1" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	



	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div>
			<a id="pnl_editinvitedform-btn_prev" class="easyui-linkbutton c8" style="width: 50px">Prev</a>
			<a id="pnl_editinvitedform-btn_next" class="easyui-linkbutton c8" style="width: 50px">Next</a>
		</div>

		<div>
			<a id="pnl_editinvitedform-btn_addnew" class="easyui-linkbutton c8" style="width: 100px">Tambah Baru</a>
		</div>

		<div>
			<a id="pnl_editinvitedform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>




</div>	
