<?php require_once dirname(__FILE__).'/payable-list.phtml' ?>
<?php require_once dirname(__FILE__).'/payable-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/payable-detilgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/payable-detilform.phtml' ?>
<?php require_once dirname(__FILE__).'/payable-billgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/payable-billform.phtml' ?>
<?php require_once dirname(__FILE__).'/payable-referencegrid.phtml' ?>
<?php require_once dirname(__FILE__).'/payable-referenceform.phtml' ?>
<?php require_once dirname(__FILE__).'/payable-responsegrid.phtml' ?>
<?php require_once dirname(__FILE__).'/payable-responseform.phtml' ?>



<div id="pnl_edit_record_custom" style="display: none">
	<div class="form_row">
		<div class="form_label_col">Commit By</div>
		<div class="form_input_col" style="border: 0px solid black">
			<span id="pnl_edit_record-commitby"></span>
		</div>
	</div>	

	<div class="form_row">
		<div class="form_label_col">Commit Date</div>
		<div class="form_input_col" style="border: 0px solid black">
			<span id="pnl_edit_record-commitdate"></span>
		</div>
	</div> 
</div>		
		
