<div id="pnl_editdetilgrid">
	<div class="fgta-page-title">Daftar Detil</div>
	<div id="pnl_editdetilgrid-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>

	<!--// Untuk keperluan search di detil
	<div id="pnl_editdetilgrid-pnl_head" style="display: flex; align-items: flex-end">
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-item" style="width: 50px;">Cari</div>
			<div class="list-search-item">
				<input id="pnl_editdetilgrid-txt_search" class="easyui-textbox" style="width: 100%">
			</div>
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_editdetilgrid-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>
		</div>
	</div>	
	//-->

	<div style="margin-top: 10px; margin-bottom: 15px">
		<table id="pnl_editdetilgrid-tbl_list" paging="true" cellspacing="0" width="100%" class="deftable">
			<thead>
				<tr>
					<th type="check">chk</th>					
					<th mapping="jurnaldetil_descr">jurnaldetil_descr</th>					
					<th mapping="jurnaldetil_validr" style="text-align: right" formatter="row_format_number">jurnaldetil_validr</th>					
				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 30px; border-bottom: 1px solid #000000; text-align: center">*</td>
					<td class="fgtable-head" style="border-bottom: 1px solid #000000">Descr</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">IDR</td>
				</tr>
			</thead>
			<tfoot>
					<tr style="background-color: #cccccc; height: 30px">
						<td class="fgtable-footer" style="width: 30px;"></td>
						<td class="fgtable-footer" style="text-align: right; padding-right: 10px;">Balance</td>
						<td class="fgtable-footer jurnal_variance" style="width: 100px; color:red; text-align: right">xxx</td>
					</tr>
					<tr style="background-color: #cccccc; height: 30px">
						<td class="fgtable-footer" style="width: 30px; border-bottom: 1px solid #000000;"></td>
						<td class="fgtable-footer" style="border-bottom: 1px solid #000000; text-align: right; padding-right: 10px;">Total</td>						
						<td class="fgtable-footer jurnal_total" style="width: 100px; border-bottom: 1px solid #000000; text-align: right">xxx</td>
					</tr>
			</tfoot>		
		</table>
	</div>

	<div id="pnl_editdetilgrid-control" style="display: flex; justify-content: space-between; margin-bottom: 100px">
		<div>
			<a id="pnl_editdetilgrid-removechecked" href="javascript:void(0)" class="easyui-linkbutton c8">Hapus Checked</a>
		</div>

		<div>
			<a id="pnl_editdetilgrid-addrow" href="javascript:void(0)" class="easyui-linkbutton c8">Tambah Baris</a>
		</div>

		<div>
		</div>

	</div>


</div>	
