<?php require_once dirname(__FILE__).'/jurnal-list.phtml' ?>
<?php require_once dirname(__FILE__).'/jurnal-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/jurnal-detilgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/jurnal-detilform.phtml' ?>
<?php require_once dirname(__FILE__).'/jurnal-referencegrid.phtml' ?>
<?php require_once dirname(__FILE__).'/jurnal-referenceform.phtml' ?>
<?php require_once dirname(__FILE__).'/jurnal-responsegrid.phtml' ?>
<?php require_once dirname(__FILE__).'/jurnal-responseform.phtml' ?>



<div id="pnl_edit_record_custom" style="display: none">
	<div class="form_row">
		<div class="form_label_col">Commit By</div>
		<div class="form_input_col" style="border: 0px solid black">
			<span id="pnl_edit_record-commitby"></span>
		</div>
	</div>	

	<div class="form_row">
		<div class="form_label_col">Commit Date</div>
		<div class="form_input_col" style="border: 0px solid black">
			<span id="pnl_edit_record-commitdate"></span>
		</div>
	</div> 

	<div class="form_row">&nbsp;</div>

	<div class="form_row">
		<div class="form_label_col">Post By</div>
		<div class="form_input_col" style="border: 0px solid black">
			<span id="pnl_edit_record-postby"></span>
		</div>
	</div>	

	<div class="form_row">
		<div class="form_label_col">Post Date</div>
		<div class="form_input_col" style="border: 0px solid black">
			<span id="pnl_edit_record-postdate"></span>
		</div>
	</div> 

</div>		
		
