<div id="pnl_list">
	<div class="fgta-page-title">Daftar Budget Project Revisi</div>

	<div id="pnl_list-pnl_head" style="display: flex; align-items: flex-end">
		<!-- Simple Query -->
		<div class="list-buttonbaru" style="text-align: right; width: calc(100% - 10px); float: right;  position: absolute">
			<a href="javascript:void(0)" id="pnl_list-btn_new" class="easyui-linkbutton c8" style="width: 60px">Baru</a>
		</div>
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-item" style="width: 50px;">Cari</div>
			<div class="list-search-item">
				<input id="pnl_list-txt_search" class="easyui-textbox" style="width: 100%">
			</div>
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_list-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>
		</div>
	</div>


	<div style="margin-top: 10px">
		<table id="pnl_list-tbl_list" paging="true" cellspacing="0" width="100%" class="deftable">
			<thead>
				<tr>
					<th mapping="projbudgetrev_id">projbudgetrev_id</th>
					<th mapping="dept_name">dept_name</th>
					<th mapping="projbudget_name">projbudget_name</th>
					<th mapping="projbudgetrev_descr">projbudgetrev_descr</th>
					<th mapping="project_name">project_name</th>
					<th mapping="projbudget_year" style="text-align: right"  formatter="row_format_number">projbudget_year</th>
					<th mapping="projbudget_month" style="text-align: right"  formatter="row_format_number">projbudget_month</th>
					<th mapping="projbudget_isdeptalloc" type="checkbox">projbudget_isdeptalloc</th>
					<th mapping="doc_name">doc_name</th>
					<th mapping="projbudgetrev_iscommit" type="checkbox">projbudgetrev_iscommit</th>
					<th mapping="projbudgetrev_isapproved" type="checkbox">projbudgetrev_isapproved</th>
					<th mapping="projbudgetrev_isclose" type="checkbox">projbudgetrev_isclose</th>

				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Dept</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Budget</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Descr/Reason</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Project</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Year</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Month</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Department Allocation</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Doc</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Commit</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Approved</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Closed</td>

				</tr>
			</thead>
		</table>
	</div>



</div>