<div id="pnl_edit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Land</div>
		<a id="pnl_edit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_edit-form">

		<div class="form_row">
			<div class="form_label_col">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_land_id" class="easyui-textbox" mapping="land_id" uppercase="true" maxlength="30" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'ID harus diisi' ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Land Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_land_name" class="easyui-textbox" mapping="land_name" uppercase="true" maxlength="90" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Nama Land harus diisi' ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Address</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_land_address" class="easyui-textbox" mapping="land_address" uppercase="true" maxlength="250" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Alamat harus diisi' ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Phone</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_land_phone" class="easyui-textbox" mapping="land_phone" uppercase="true" maxlength="30" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Phone harus diisi' ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Email</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_land_email" class="easyui-textbox" mapping="land_email" uppercase="true" maxlength="150" style="width: 400px" data-options="multiline: false  ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_land_isdisabled" class="easyui-checkbox c1" mapping="land_isdisabled" data-options="label: 'Disabled', labelPosition: 'after', disabled:false, checked: false ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Geo Location</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_land_geoloc" class="easyui-textbox" mapping="land_geoloc"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Land Type</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_landtype_id" class="easyui-combo" style="width: 400px" mapping="landtype_id" display="landtype_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Type Land harus diisi', prompt: '-- PILIH --'">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Zone</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_zone_id" class="easyui-combo" style="width: 400px" mapping="zone_id" display="zone_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Zone harus diisi', prompt: '-- PILIH --'">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">City</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_city_id" class="easyui-combo" style="width: 400px" mapping="city_id" display="city_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'City harus diisi', prompt: '-- PILIH --'">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Partner</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_partner_id" class="easyui-combo" style="width: 400px" mapping="partner_id" display="partner_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Partner harus diisi', prompt: '-- PILIH --'">
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_edit-btn_save" class="easyui-linkbutton c1" style="width">Simpan</a>
		</div>
	</div>	





	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol yang lin disini -->
		</div>
		<div>
			<a id="pnl_edit-btn_delete" class="easyui-linkbutton c5" style="width">Hapus</a>
		</div>
	</div>

</div>

