<?php require_once dirname(__FILE__).'/cashdiscount-list.phtml' ?>
<?php require_once dirname(__FILE__).'/cashdiscount-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/cashdiscount-approvalgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/cashdiscount-approvalform.phtml' ?>





<div id="pnl_edit_record_custom" style="display: none">
	<div class="form_row">
		<div class="form_label_col">Commit By</div>
		<div class="form_input_col" style="border: 0px solid black">
			<span id="pnl_edit_record-commitby"></span>
		</div>
	</div>	

	<div class="form_row">
		<div class="form_label_col">Commit Date</div>
		<div class="form_input_col" style="border: 0px solid black">
			<span id="pnl_edit_record-commitdate"></span>
		</div>
	</div> 

	<div class="form_row" style="margin-top: 30px;">
		<div class="form_label_col">Approve By</div>
		<div class="form_input_col" style="border: 0px solid black">
			<span id="pnl_edit_record-closedby"></span>
		</div>
	</div>	

	<div class="form_row">
		<div class="form_label_col">Approve Date</div>
		<div class="form_input_col" style="border: 0px solid black">
			<span id="pnl_edit_record-closedate"></span>
		</div>
	</div>	
</div>