<?php

	$doc_iso_reg = "<yout form iso number>";
	$report_title['id'] = "Aging AR by Advertiser";
	$report_title['en'] = "";

	$report_printid = strtoupper(uniqid());
	$report_printdate = date('d/m/Y');
	$report_date =$report_printdate;

	$doc_descr = "per tanggal $report_printdate";
?>

<script>
global.reportparameter = {
	rpttype: '<?=$this->reportparameter->rpttype?>',
	filter_id: '<?=$this->reportparameter->filter_id?>',
	date: '<?=$this->reportparameter->date?>'
}
</script>



<div style="position: absolute; z-index: 1">
	<div  id="pagemeasure">&nbsp;</div>
</div>


<div id="wrapper" style="z-index: 10">
	<!-- page header: selalu ditampilkan pada tiap halaman, kecuali halaman 1 -->
	<div id="pageheader" class="fullwidth">
		<div>
			<div><?=$report_title['id']?></div>
			<div style="font-style: italic"><?=$doc_descr?></div>
		</div>
		<div style="text-align: right; width: 70mm;">
			<div style="display:inline-block; width: 38mm;"><b>Print Id</b> <?=$report_printid?></div>
			<div style="display:inline-block; width: 30mm;">&nbsp;</div>
			
		</div>
	</div>


	<!-- report header --->
	<div id="reporttitle" class="fullwidth">
		<div style="display: flex; justify-content: space-between">
			<div >
				<div style="font-weight: bold; font-size: 12pt; "><?=__COMPANY_NAME__?></div>
				<div style="font-weight: bold; font-size: 12pt; margin-top: 2mm"><?=$report_title['id']?></div>
			</div>	
			<div style="text-align: right">
				<div style="text-align: right; font-size: 8pt"><b>Print Id</b> <?=$report_printid?></div>
				<!-- <img id="ellogo" src="index.php/public/assets/logo-printform-right.svg"> -->
			</div>			
		</div>
	</div>


	<div class="fullwidth" style="position: relative; margin-top: 2mm; ">
		<div style="display: flex; justify-content: space-between">
			<div style="font-size: 8pt;"><b>per tanggal</b> <?=$report_date?></div>
			<div style="font-size: 8pt;"><b>Page</b> 1 <b>of</b> <span id="reporttotalpage">1</span></div>
		</div>
	</div>



	<!-- report content -->
	<div id="reportcontent" class="fullwidth">
		<table id="obj_reporttable" width="100%">
			<thead>
				<tr>
					<td class="col_head" colspan="12">&nbsp;</td>
				</tr>
			</thead>
			<tbody id="obj_reporttable_tbody">


			</tbody>

		</table>
		<script>global.totalrowcount = 0</script>
	</div>


</div>

<div id="wrapperfooter" class="fullwidth" style="z-index: 20">
	<div id="reportfooter" style="display: flex; justify-content: space-between; height: 10mm; ">
		&nbsp;
	<div>				
</div>