<?php

	$doc_iso_reg = "<yout form iso number>";
	$report_title['id'] = "Aging AR by Brand";
	$report_title['en'] = "";

	$report_printid = strtoupper(uniqid());
	$report_printdate = date('d/m/Y');

	$doc_descr = "per tanggal $report_printdate";
?>

<script>
global.reportparameter = {
	rpttype: '<?=$this->reportparameter->rpttype?>',
	filter_id: '<?=$this->reportparameter->filter_id?>',
	date: '<?=$this->reportparameter->date?>'
}
</script>



<div style="position: absolute; z-index: 1">
	<div  id="pagemeasure">&nbsp;</div>
</div>


<div id="wrapper" style="z-index: 10">
	<!-- page header: selalu ditampilkan pada tiap halaman, kecuali halaman 1 -->
	<div id="pageheader" class="fullwidth">
		<div>
			<div><?=$report_title['id']?></div>
			<div style="font-style: italic"><?=$doc_descr?></div>
		</div>
		<div style="text-align: right; width: 70mm;">
			<div style="display:inline-block; width: 38mm;"><b>Print Id</b> <?=$report_printid?></div>
			<div style="display:inline-block; width: 30mm;">&nbsp;</div>
			
		</div>
	</div>


	<!-- report header --->
	<div id="reporttitle" class="fullwidth">
		<div style="display: flex; justify-content: space-between">

			<div >
				<div style="font-size: 7pt; font-style: italic"><?=$doc_iso_reg?></div>
				<div style="font-weight: bold; font-size: 12pt; margin-top: 2mm"><?=$report_title['id']?></div>
				<div style="font-weight: bold; font-style: italic; font-size: 10pt; color: #666"><?=$report_title['en']?></div>
			</div>	
			<div style="text-align: right">
				<!-- <img id="ellogo" src="index.php/public/assets/logo-printform-right.svg"> -->
			</div>			
		</div>
	</div>


	<div class="fullwidth" style="position: relative; margin-top: 2mm; ">
		<div style="font-size: 8pt;">
			<b>per tanggal</b> ....
		</div>
		<div style="display: flex; justify-content: space-between; margin-top: 2mm">
			<div style="font-size: 8pt;"><b>Page</b> 1 <b>of</b> <span id="reporttotalpage">1</span></div>
			<div style="text-align: right; font-size: 8pt"><b>Print Id</b> <?=$report_printid?></div>
		</div>
	</div>


	<!-- report content -->
	<div id="reportcontent" class="fullwidth">
		<table id="obj_reporttable" width="100%">
			<thead>
				<tr>
					<td class="col_head">Brand<br>Agency</td>
					<td class="col_head">Advertiser</td>
					<td class="col_head">Keterangan</td>
					<td class="col_head">Date</td>
					<td class="col_head date">Days</td>
					<td class="col_head val">Current</td>
					<td class="col_head val">0-30</td>
					<td class="col_head val">31-60</td>
					<td class="col_head val">61-90</td>
					<td class="col_head val">91-120</td>
					<td class="col_head val">>120</td>
					<td class="col_head val total">Outstanding</td>
				</tr>
			</thead>
			<tbody id="obj_reporttable_tbody">


			</tbody>
		</table>
		<script>global.totalrowcount = 0</script>
	</div>


</div>

<div id="wrapperfooter" class="fullwidth" style="z-index: 20">
	<div id="reportfooter" style="display: flex; justify-content: space-between; height: 10mm; ">
		&nbsp;
	<div>				
</div>