<style>
	.login-wrapper {
		position: fixed;
		overflow-Y: scroll;
		/*border: 3px solid #ff2a2a; */
		display:flex;
		width: calc(100vw - (100vw - 100%));
		height: 100vh;
		align-items: center;
		justify-content: center;
		/* background-color: #000	; */
		background: #efefef url('index.php/public/assets/bg-map.jpg')  fixed;
		-webkit-background-size: 1024px 768px;
		-moz-background-size: 1024px 768px;
		-o-background-size: 1024px 768px;
		background-size: 1024px 768px;
		
		
		-webkit-touch-callout: none; /* iOS Safari */
		-webkit-user-select: none; /* Safari */
		-khtml-user-select: none; /* Konqueror HTML */
		-moz-user-select: none; /* Old versions of Firefox */
		-ms-user-select: none; /* Internet Explorer/Edge */
		user-select: none; /* Non-prefixed version, currently
								supported by Chrome, Edge, Opera and Firefox */	

	}

	.login-box {
		margin: 20px; width: 250px; 
		border: 1px solid #62000D; 
		padding-bottom: 25px; 
		background-color: rgba(230,230,230, .5);
		border-bottom-right-radius: 25px;
		box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
	}


	@media screen and (max-width: 520px) {
		.login-wrapper {
			border: 0px;
			align-items: flex-start;
			justify-content: flex-start;
			padding: 0px;	
			background-color: #ffffff			
		}

		.login-box {
			margin: 0px;
			width: 100%;
			border: 0px;
			padding: 0px;
			box-shadow: none;
		}
	}




	.email-login {
		position:relative;
		float: left;
		width: 100%;
		height:auto;
		margin-top: 20px;
		text-align:center;
}



	.u-form-group{
		width:100%;
		margin-bottom: 10px;


	}


	.u-form-group input[type="checkbox"] {
		line-height: 2.1ex;
		position: absolute;
    	left: -999em;		
	}

	input[type="checkbox"] + label {
		position: relative;
		overflow: hidden;
		cursor: pointer;
	}

	.u-form-group input[type="checkbox"]:checked + label::after {
		content: '';
		position: absolute;
		width: 1.2ex;
		height: 0.4ex;
		background: rgba(0, 0, 0, 0);
		top: 0.5ex;
		left: 0.6ex;
		border: 3px solid #624568;
		border-top: none;
		border-right: none;
		-webkit-transform: rotate(-45deg);
		-moz-transform: rotate(-45deg);
		-o-transform: rotate(-45deg);
		-ms-transform: rotate(-45deg);
		transform: rotate(-45deg);
	}


	.u-form-group input[type="checkbox"] + label::before {
		content: "";
		display: inline-block;
		vertical-align: -25%;
		height: 2ex;
		width: 2ex;
		background-color: white;
		border: 1px solid rgb(166, 166, 166);
		border-radius: 2px;
		/* box-shadow: inset 0 2px 5px rgba(0,0,0,0.25);  */
		margin-right: 0.5em;
	}


	.u-form-group input[type="text"],
	.u-form-group input[type="password"]{
		width: 100%;
		height:45px;
		outline: none;
		border: 1px solid #ddd;
		padding: 0 10px;
		border-radius: 2px;
		color: #333;
		font-size:0.8rem;
		-webkit-transition:all 0.1s linear;
		-moz-transition:all 0.1s linear;
		transition:all 0.1s linear;
	}

	.u-form-group input:focus{
		border-color: #da99e9;
	}

	.u-form-group button{
		width:100%;
		border: none;
		outline: none;
		color: #fff;
		font-size: 14px;
		font-weight: normal;
		padding: 14px 0;
		border-radius: 2px;
		text-transform: uppercase;
	}	




	.c8,.c8:hover,.c8>.panel-header{
		color: #fff;
		border-color: #3A0008;
		background: #3A0008;
		background: -webkit-linear-gradient(top,#62000D 0, #3A0008 100%);
		background: -moz-linear-gradient(top,#62000D 0,#3A0008 100%);
		background: -o-linear-gradient(top,#62000D 0,#3A0008 100%);
		background: linear-gradient(to bottom,#62000D 0,#3A0008 100%);
		filter: progid:DXImageTransform.Microsoft.gradient(startColorstr=#62000D,endColorstr=#3A0008,GradientType=0);
	}
	a.c8:hover{
		background: #3A0008;
		filter: none;
	}
	.c8>.panel-body{
		border-color: #3A0008;
	}
	.c8>.dialog-toolbar,.c8>.dialog-button{
		border-left-color: #3A0008;
		border-right-color: #3A0008;
	}
	.c8>.dialog-button{
		border-bottom-color: #3A0008;
	}
</style>


<div class="login-wrapper">


	<div class="login-box" >

		<div style="font-weight: bold; font-size: larger; margin-bottom: 18px; height: 85px; background-color: #62000D; text-align: right;
		background-image: url('index.php/public/assets/-login-onesolution.jpg');
		background-size: 520px 116px;
		background-position:  top left;
		background-repeat: no-repeat;
		">
			<!-- <img src="images/kalista.png" width="210px" height="116px" border="0px"> -->
		</div>


		<div style="padding: 15px 15px 15px 15px; ">
			<div class="u-form-group">
				<input  id="txt_username" type="text" placeholder="Username"/>
			</div>

			<div class="u-form-group">
				<input id="txt_password" type="password" placeholder="Password"/>
			</div>

			<div class="u-form-group">	
				<input type="checkbox" id="chk_rememberme">
				<label for="chk_rememberme">Remember me</label>
			</div>

			<div class="u-form-group" style="margin-top: 35px">
				<button  id="btn_login" class="c8">Login</button>
			</div>


		</div>


	</div> 


</div>
