<div id="pnl_list">
	<div class="fgta-page-title">Daftar sales Order</div>

	<div id="pnl_list-pnl_head" style="display: flex; align-items: flex-end">
		<!-- Simple Query -->
		<div class="list-buttonbaru" style="text-align: right; width: calc(100% - 10px); float: right;  position: absolute">
			<a href="javascript:void(0)" id="pnl_list-btn_new" class="easyui-linkbutton c8" style="width: 60px">Baru</a>
		</div>
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-item" style="width: 50px;">Cari</div>
			<div class="list-search-item">
				<input id="pnl_list-txt_search" class="easyui-textbox" style="width: 100%">
			</div>
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_list-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>
		</div>
	</div>


	<div style="margin-top: 10px">
		<table id="pnl_list-tbl_list" paging="true" cellspacing="0" width="100%" class="deftable">
			<thead>
				<tr>
					<th mapping="salesorder_id">salesorder_id</th>
					<th mapping="salesorder_date">salesorder_date</th>
					<th mapping="salesorder_descr">salesorder_descr</th>
					<th mapping="salesorder_ref">salesorder_ref</th>
					<th mapping="salesorder_istax" type="checkbox">salesorder_istax</th>
					<th mapping="salesordertype_name">salesordertype_name</th>
					<th mapping="dept_name">dept_name</th>
					<th mapping="salesorder_iscommit" type="checkbox">salesorder_iscommit</th>
					<th mapping="salesorder_isapprovalprogress" type="checkbox">salesorder_isapprovalprogress</th>
					<th mapping="salesorder_isapproved" type="checkbox">salesorder_isapproved</th>
					<th mapping="salesorder_isdeclined" type="checkbox">salesorder_isdeclined</th>
					<th mapping="salesorder_isclose" type="checkbox">salesorder_isclose</th>

				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Date</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Descr</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Ref</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Tax</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Order Type</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Dept</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Commit</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Progress</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Approved</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Declined</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Close</td>

				</tr>
			</thead>
		</table>
	</div>



</div>