-- SET FOREIGN_KEY_CHECKS=0;

-- drop table if exists `trn_orderin`;


CREATE TABLE `trn_orderin` (
	`orderin_id` varchar(30) NOT NULL , 
	`unit_id` varchar(10)  , 
	`orderintype_id` varchar(10)  , 
	`orderin_ref` varchar(90)  , 
	`orderin_descr` varchar(90)  , 
	`orderin_dtstart` date NOT NULL , 
	`orderin_dtend` date NOT NULL , 
	`partner_id` varchar(30)  , 
	`ae_empl_id` varchar(14)  , 
	`trxmodel_id` varchar(10) NOT NULL , 
	`project_id` varchar(30)  , 
	`ppn_taxtype_id` varchar(10)  , 
	`ppn_taxvalue` decimal(4, 2) NOT NULL DEFAULT 0, 
	`ppn_include` tinyint(1) NOT NULL DEFAULT 0, 
	`pph_taxtype_id` varchar(10)  , 
	`pph_taxvalue` decimal(4, 2) NOT NULL DEFAULT 0, 
	`sales_coa_id` varchar(10) NOT NULL , 
	`salesdisc_coa_id` varchar(10)  , 
	`ppn_coa_id` varchar(10)  , 
	`ppnsubsidi_coa_id` varchar(10)  , 
	`pph_coa_id` varchar(10)  , 
	`sales_dept_id` varchar(30) NOT NULL , 
	`orderin_totalitem` int(5) NOT NULL DEFAULT 0, 
	`orderin_totalqty` int(5) NOT NULL DEFAULT 0, 
	`orderin_salesgross` decimal(16, 0) NOT NULL DEFAULT 0, 
	`orderin_discount` decimal(16, 0) NOT NULL DEFAULT 0, 
	`orderin_subtotal` decimal(16, 0) NOT NULL DEFAULT 0, 
	`orderin_pph` decimal(16, 0) NOT NULL DEFAULT 0, 
	`orderin_nett` decimal(16, 0) NOT NULL DEFAULT 0, 
	`orderin_ppn` decimal(16, 0) NOT NULL DEFAULT 0, 
	`orderin_total` decimal(16, 0) NOT NULL DEFAULT 0, 
	`orderin_totaladdcost` decimal(16, 0) NOT NULL DEFAULT 0, 
	`orderin_payment` decimal(16, 0) NOT NULL DEFAULT 0, 
	`orderin_version` int(4) NOT NULL DEFAULT 0, 
	`orderin_isdateinterval` tinyint(1) NOT NULL DEFAULT 0, 
	`orderin_iscommit` tinyint(1) NOT NULL DEFAULT 0, 
	`orderin_commitby` varchar(14)  , 
	`orderin_commitdate` datetime  , 
	`orderin_isclose` tinyint(1) NOT NULL DEFAULT 0, 
	`orderin_closeby` varchar(14)  , 
	`orderin_closedate` datetime  , 
	`orderin_isautogenerated` tinyint(1) NOT NULL DEFAULT 0, 
	`_createby` varchar(13) NOT NULL , 
	`_createdate` datetime NOT NULL DEFAULT current_timestamp(), 
	`_modifyby` varchar(13)  , 
	`_modifydate` datetime  , 
	PRIMARY KEY (`orderin_id`)
) 
ENGINE=InnoDB
COMMENT='Daftar Order Pembelian, Sewa, Service, Talent, dll';

ALTER TABLE `trn_orderin` ADD KEY `unit_id` (`unit_id`);
ALTER TABLE `trn_orderin` ADD KEY `orderintype_id` (`orderintype_id`);
ALTER TABLE `trn_orderin` ADD KEY `partner_id` (`partner_id`);
ALTER TABLE `trn_orderin` ADD KEY `ae_empl_id` (`ae_empl_id`);
ALTER TABLE `trn_orderin` ADD KEY `trxmodel_id` (`trxmodel_id`);
ALTER TABLE `trn_orderin` ADD KEY `project_id` (`project_id`);
ALTER TABLE `trn_orderin` ADD KEY `ppn_taxtype_id` (`ppn_taxtype_id`);
ALTER TABLE `trn_orderin` ADD KEY `pph_taxtype_id` (`pph_taxtype_id`);
ALTER TABLE `trn_orderin` ADD KEY `sales_coa_id` (`sales_coa_id`);
ALTER TABLE `trn_orderin` ADD KEY `salesdisc_coa_id` (`salesdisc_coa_id`);
ALTER TABLE `trn_orderin` ADD KEY `ppn_coa_id` (`ppn_coa_id`);
ALTER TABLE `trn_orderin` ADD KEY `ppnsubsidi_coa_id` (`ppnsubsidi_coa_id`);
ALTER TABLE `trn_orderin` ADD KEY `pph_coa_id` (`pph_coa_id`);
ALTER TABLE `trn_orderin` ADD KEY `sales_dept_id` (`sales_dept_id`);

ALTER TABLE `trn_orderin` ADD CONSTRAINT `fk_trn_orderin_mst_unit` FOREIGN KEY (`unit_id`) REFERENCES `mst_unit` (`unit_id`);
ALTER TABLE `trn_orderin` ADD CONSTRAINT `fk_trn_orderin_mst_orderintype` FOREIGN KEY (`orderintype_id`) REFERENCES `mst_orderintype` (`orderintype_id`);
ALTER TABLE `trn_orderin` ADD CONSTRAINT `fk_trn_orderin_mst_partner` FOREIGN KEY (`partner_id`) REFERENCES `mst_partner` (`partner_id`);
ALTER TABLE `trn_orderin` ADD CONSTRAINT `fk_trn_orderin_mst_empl` FOREIGN KEY (`ae_empl_id`) REFERENCES `mst_empl` (`empl_id`);
ALTER TABLE `trn_orderin` ADD CONSTRAINT `fk_trn_orderin_mst_trxmodel` FOREIGN KEY (`trxmodel_id`) REFERENCES `mst_trxmodel` (`trxmodel_id`);
ALTER TABLE `trn_orderin` ADD CONSTRAINT `fk_trn_orderin_mst_project` FOREIGN KEY (`project_id`) REFERENCES `mst_project` (`project_id`);
ALTER TABLE `trn_orderin` ADD CONSTRAINT `fk_trn_orderin_mst_taxtype` FOREIGN KEY (`ppn_taxtype_id`) REFERENCES `mst_taxtype` (`taxtype_id`);
ALTER TABLE `trn_orderin` ADD CONSTRAINT `fk_trn_orderin_mst_taxtype_2` FOREIGN KEY (`pph_taxtype_id`) REFERENCES `mst_taxtype` (`taxtype_id`);
ALTER TABLE `trn_orderin` ADD CONSTRAINT `fk_trn_orderin_mst_coa` FOREIGN KEY (`sales_coa_id`) REFERENCES `mst_coa` (`coa_id`);
ALTER TABLE `trn_orderin` ADD CONSTRAINT `fk_trn_orderin_mst_coa_2` FOREIGN KEY (`salesdisc_coa_id`) REFERENCES `mst_coa` (`coa_id`);
ALTER TABLE `trn_orderin` ADD CONSTRAINT `fk_trn_orderin_mst_coa_3` FOREIGN KEY (`ppn_coa_id`) REFERENCES `mst_coa` (`coa_id`);
ALTER TABLE `trn_orderin` ADD CONSTRAINT `fk_trn_orderin_mst_coa_4` FOREIGN KEY (`ppnsubsidi_coa_id`) REFERENCES `mst_coa` (`coa_id`);
ALTER TABLE `trn_orderin` ADD CONSTRAINT `fk_trn_orderin_mst_coa_5` FOREIGN KEY (`pph_coa_id`) REFERENCES `mst_coa` (`coa_id`);
ALTER TABLE `trn_orderin` ADD CONSTRAINT `fk_trn_orderin_mst_dept` FOREIGN KEY (`sales_dept_id`) REFERENCES `mst_dept` (`dept_id`);





