<?php namespace FGTA4\module; 
if (!defined('FGTA4')) {
	die('Forbiden');
}
?><!DOCTYPE HTML>
<html>
	<head>
		
		<title><?=$this->title?></title>
		<!-- <base href="<?=__BASEADDRESS?>"> -->
		<base href="<?php echo $_SERVER['REQUEST_SCHEME'].'://'.$_SERVER['HTTP_HOST'].str_replace(basename($_SERVER['SCRIPT_NAME']), '', $_SERVER['SCRIPT_NAME']); ?> ">
		<link rel="shortcut icon" href="favicon.ico">
		<link rel="manifest" href="manifest.json">
		<!-- <link rel="icon" sizes="192x192" href="images/<?=__ICON32?>">
		<link rel="apple-touch-icon" sizes="192x192" href="images/<?=__ICON32?>">
		 -->
		<meta name="mobile-web-app-capable" content="yes">
		<meta name="apple-mobile-web-app-capable" content="yes">
		<meta name="application-name" content="<?=__APPDISPLAYNAME?>">
		<meta name="apple-mobile-web-app-title" content="<?=__APPDISPLAYNAME?>">
		<meta name="theme-color" content="#9c6ea7">
		<meta name="msapplication-navbutton-color" content="#9c6ea7">
		<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
		<meta name="msapplication-starturl" content="/">

		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
		<meta http-equiv="Pragma" content="no-cache" />
		<meta http-equiv="Expires" content="-1" />
		<meta name="modulefullname" content="<?=$this->reqinfo->modulefullname?>" />
		<meta name="variancename" content="<?=$this->reqinfo->variancename?>" />
		<meta name="basetitle" content="<?=$this->configuration->basetitle?>" />
		<meta name="home" content="<?=__STARTMODULE?>" />

		<style>
			@font-face {
				font-family: 'Droid Sans';
				font-style: normal;
				font-weight: 300;
				src: local('Droid Sans Regular'), local('DroidSans-Regular'), url('./templates/fgta-content/asset/droidsans.woff2') format('woff2');
				unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;	
				font-stretch: condensed;
			}

			html, body {
				width: 100%;
				height: 100%;
				padding: 0px;
				margin: 0 auto;
				font-family: Droid Sans; 
			}
		</style>


		<?php
		$app_css_path = __LOCAL_PUBLIC_DIR . "/style-content.css";
		if (\is_file($app_css_path)) {
		?>
		<link rel="stylesheet" type="text/css" href="index.php/public/style-content.css" />
		<?php } ?>		

		<script src="index.php/jslibs/cookie.js"></script>
	</head>

	
	<body style="display:flex; flex-direction:column">
		<?php
		$tp_header_path = __LOCAL_PUBLIC_DIR . "/page-header.phtml";
		if (\is_file($tp_header_path)) {
			require_once $tp_header_path;
		} else { ?>
		<header id="page-header">
			blank header
		</header>
		<?php } ?>


		<?php
		$tp_content_path = __LOCAL_PUBLIC_DIR . "/page-content.phtml";
		if (\is_file($tp_content_path)) {
			require_once $tp_content_path;
		} else { ?>
		<main id="page-content" >
			content
		</main>
		<?php } ?>


		<?php
		$tp_footer_path = __LOCAL_PUBLIC_DIR . "/page-footer.phtml";
		if (\is_file($tp_footer_path)) {
			require_once $tp_footer_path;
		} else { ?>
		<footer id="page-footer">
			blank footer
		</footer>
		<?php } ?>		
	</body>
</html>	