<?php

	$doc_iso_reg = "<yout form iso number>";
	$report_title['id'] = "NERACA";
	$report_title['en'] = "";

	$report_printid = strtoupper(uniqid());
	$report_printdate = date('d/m/Y');
	$report_date = $this->report_date;

	$doc_descr = "per tanggal $report_printdate";
?>



<div style="position: absolute; z-index: 1">
	<div  id="pagemeasure">&nbsp;</div>
</div>


<div id="wrapper" style="z-index: 10">

	<!-- page header: selalu ditampilkan pada tiap halaman, kecuali halaman 1 -->
	<div id="pageheader" class="fullwidth">
		<div>
			<div><?=$report_title['id']?></div>
			<div style="font-style: italic"><?=$doc_descr?></div>
		</div>
		<div style="text-align: right; width: 70mm;">
			<div style="display:inline-block; width: 38mm;"><b>Print Id</b> <?=$report_printid?></div>
			<div style="display:inline-block; width: 30mm;">&nbsp;</div>
		</div>
	</div>


	<!-- report header --->
	<div id="reporttitle" class="fullwidth">
		<div style="display: flex; justify-content: space-between">
			<div >
				<div style="font-weight: bold; font-size: 12pt; "><?=__COMPANY_NAME__?></div>
				<div style="font-weight: bold; font-size: 12pt; margin-top: 2mm"><?=$report_title['id']?></div>
			</div>	
			<div style="text-align: right">
				<div style="text-align: right; font-size: 8pt"><b>Print Id</b> <?=$report_printid?></div>
			<!-- <img id="ellogo" src="index.php/public/assets/logo-printform-right.svg"> -->
			</div>			
		</div>
	</div>


	<div class="fullwidth" style="position: relative; margin-top: 2mm; ">
		<div style="display: flex; justify-content: space-between">
			<div style="font-size: 8pt;"><b>per tanggal</b> <?=$report_date?></div>
			<div style="font-size: 8pt;"><b>Page</b> 1 <b>of</b> <span id="reporttotalpage">1</span></div>
		</div>
	</div>



	<!-- report content -->
	<div id="reportcontent" class="fullwidth">
		<table id="obj_reporttable" width="100%" data-cols-width="10,20,60,30">
			<thead>
				<tr>
					<th class="rowhead ptdata-col-no" data-fill-color='CCCCCC'>No</th>
					<th class="rowhead rptdata-col-coaname" data-fill-color='CCCCCC'>Group 2</th>
					<th class="rowhead rptdata-col-val" data-fill-color='CCCCCC'>Saldo</th>
				</tr>

			</thead>
			<tbody>
				<?php 
				$i=0;
				foreach ($this->rows as $row) { 
					$i++;
					$namestyle = "";
					$amountstyle = "";

					$namestyle .= ($row['coaformatset_isbold']=="1") ? "font-weight:bold;" : "";
					$namestyle .= ($row['coaformatset_isitalic']=="1") ? "font-style:italic;" : "";
					$namestyle .= ($row['coaformatset_isunderline']=="1") ? "text-decoration:underline;" : "";

					$amountstyle .= ($row['coaformatset_isbold']=="1") ? "font-weight:bold;" : "";
					$amountstyle .= ($row['coaformatset_isitalic']=="1") ? "font-style:italic;" : "";
					$amountstyle .= ($row['coaformatset_isunderline']=="1") ? "text-decoration:underline;"  : "";


					$indent = 20 * $row['coaformatset_indent'];


					$saldoakhir_idr = number_format($row['saldoakhir_idr']);
					if ($row['coaformatset_coacount']<=0) {
						$saldoakhir_idr = "<span></span>";
					} 
				?>


					
				<tr>
					<td><?=$i?></td>

					<?php if ($row['coaformatset_isblankline']=="1") { ?>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
					<?php } else { ?>
						<td><div style="margin-left: <?=$indent?>px;<?=$namestyle?>"><?=$row['coaformatset_name']?></div></td>
						<td style="text-align: right; <?=$amountstyle?>"><?=$saldoakhir_idr?></td>
					<?php } ?> 
				</tr>	

				<?php } ?>
			</tbody>
			<tfoot>
			</tfoot>			
		</table>
		<script>global.totalrowcount = '<?=($i-1)?>'</script>
	</div>


</div>

<div id="wrapperfooter" class="fullwidth" style="z-index: 20">
	<div id="reportfooter" style="display: flex; justify-content: space-between; height: 10mm; ">
		&nbsp;
	<div>				
</div>



