<div id="pnl_list">
	<div class="fgta-page-title">Daftar Tanda Terima Sementara</div>

	<div id="pnl_list-pnl_head" style="display: flex; align-items: flex-end">
		<!-- Simple Query -->
		<div class="list-buttonbaru" style="text-align: right; width: calc(100% - 10px); float: right;  position: absolute">
			<a href="javascript:void(0)" id="pnl_list-btn_new" class="easyui-linkbutton c8" style="width: 60px">Baru</a>
		</div>
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-item" style="width: 50px;">Cari</div>
			<div class="list-search-item">
				<input id="pnl_list-txt_search" class="easyui-textbox" style="width: 100%">
			</div>
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_list-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>
		</div>
	</div>


	<div style="margin-top: 10px">
		<table id="pnl_list-tbl_list" paging="true" cellspacing="0" width="100%">
			<thead>
				<tr>
					<!-- <th mapping="temprecv_id">temprecv_id</th> -->
					<th mapping="temprecv_date">temprecv_date</th>
					<th mapping="temprecv_descr">temprecv_descr</th>
					<th mapping="temprecv_validrtotal" style="text-align: right"  formatter="row_format_number">temprecv_validrtotal</th>

					<!-- <th mapping="temprecv_isadvance" type="checkbox">temprecv_isadvance</th>
					<th mapping="temprecv_iscommit" type="checkbox">temprecv_iscommit</th>
					<th mapping="temprecv_isverify" type="checkbox">temprecv_isverify</th>
					<th mapping="paymtype_name">paymtype_name</th>
					<th mapping="partner_name">partner_name</th>
					<th mapping="coa_name">coa_name</th>
					<th mapping="trxmodel_name">trxmodel_name</th> -->

				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<!-- <td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td> -->
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Date</td>
					<td class="fgtable-head" style="border-bottom: 1px solid #000000">Descr</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">IDR</td>
					<!-- <td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Advance</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Commit</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Verify</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Tipe Payment</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Partner</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">COA</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">TrxModel</td> -->

				</tr>
			</thead>
		</table>
	</div>



</div>