<?php

	$doc_iso_reg = "<yout form iso number>";
	$report_title['id'] = "TRIAL BALANCE";
	$report_title['en'] = "";

	$report_printid = strtoupper(uniqid());
	$report_printdate = date('d/m/Y');
	$report_date = $this->report_date;

	$doc_descr = "per tanggal $report_printdate";
?>



<div style="position: absolute; z-index: 1">
	<div  id="pagemeasure">&nbsp;</div>
</div>


<div id="wrapper" style="z-index: 10">

	<!-- page header: selalu ditampilkan pada tiap halaman, kecuali halaman 1 -->
	<div id="pageheader" class="fullwidth">
		<div>
			<div><?=$report_title['id']?></div>
			<div style="font-style: italic"><?=$doc_descr?></div>
		</div>
		<div style="text-align: right; width: 70mm;">
			<div style="display:inline-block; width: 38mm;"><b>Print Id</b> <?=$report_printid?></div>
			<div style="display:inline-block; width: 30mm;">&nbsp;</div>
			
		</div>
	</div>


	<!-- report header --->
	<div id="reporttitle" class="fullwidth">
		<div style="display: flex; justify-content: space-between">

			<div >
				<div style="font-size: 7pt; font-style: italic"><?=$doc_iso_reg?></div>
				<div style="font-weight: bold; font-size: 12pt; margin-top: 2mm"><?=$report_title['id']?></div>
				<div style="font-weight: bold; font-style: italic; font-size: 10pt; color: #666"><?=$report_title['en']?></div>
			</div>	
			<div style="text-align: right">
				<!-- <img id="ellogo" src="index.php/public/assets/logo-printform-right.svg"> -->
			</div>			
		</div>
	</div>


	<div class="fullwidth" style="position: relative; margin-top: 2mm; ">
		<div style="font-size: 8pt;">
			<b>per tanggal</b> <?=$report_date?>
		</div>
		<div style="display: flex; justify-content: space-between; margin-top: 2mm">
			<div style="font-size: 8pt;"><b>Page</b> 1 <b>of</b> <span id="reporttotalpage">1</span></div>
			<div style="text-align: right; font-size: 8pt"><b>Print Id</b> <?=$report_printid?></div>
		</div>
	</div>



	<!-- report content -->
	<div id="reportcontent" class="fullwidth">
		<table id="obj_reporttable" width="100%" data-cols-width="10,20,60,30,30,30,30">
			<thead>
				<tr>
					<th class="rowhead ptdata-col-no" data-fill-color='CCCCCC'>No</th>
					<th class="rowhead rptdata-col-coacode" data-fill-color='CCCCCC'>Kode COA</th>
					<th class="rowhead rptdata-col-coaname" data-fill-color='CCCCCC'>Account</th>
					<th class="rowhead rptdata-col-coaname" data-fill-color='CCCCCC'>Partner</th>
					<th class="rowhead rptdata-col-val" data-fill-color='CCCCCC'>Saldo Awal</th>
					<th class="rowhead rptdata-col-val" data-fill-color='CCCCCC'>Debet</th>
					<th class="rowhead rptdata-col-val" data-fill-color='CCCCCC'>Kredit</th>
					<th class="rowhead rptdata-col-val" data-fill-color='CCCCCC'>Saldo Akhir</th>
				</tr>
			</thead>
			<tbody>
				<!-- 45 -->
				<?php 
				$i=0;
				$total_saldoawal = 0;
				$total_debet = 0;
				$total_kredit = 0;
				$total_saldoakhir = 0;
				foreach ($this->rows as $row) { 
					$i++;

					$row['debet'] = ($row['mutasi']>=0) ? $row['mutasi'] : 0;
					$row['kredit'] = ($row['mutasi']<0) ? -$row['mutasi'] : 0;
					
					$total_saldoawal += $row['saldoawal'];
					$total_debet += $row['debet'];
					$total_kredit += $row['kredit'];
					$total_saldoakhir += $row['saldoakhir'];
				?>
				<tr id="tb_row_<?=$i?>">
					<td class="row rptdata-col-no"><?=$i?></td>
					<td class="row rptdata-col-decoacodescr"><?=$row['coa_id']?></td>
					<td class="row rptdata-col-coaname"><?=$row['coa_name']?></td>
					<td class="row rptdata-col-coaname"><?=$row['partner_name']?></td>
					<td class="row rptdata-col-val" data-t="n" data-num-fmt="#,##0"><?=number_format($row['saldoawal'])?></td>
					<td class="row rptdata-col-val" data-t="n" data-num-fmt="#,##0"><?=number_format($row['debet'])?></td>
					<td class="row rptdata-col-val" data-t="n" data-num-fmt="#,##0"><?=number_format($row['kredit'])?></td>
					<td class="row rptdata-col-val" data-t="n" data-num-fmt="#,##0"><?=number_format($row['saldoakhir'])?></td>
				</tr>
				<?php } ?>

				<tr>
					<td class="rowfoot" colspan="4" style="text-align: center" data-fill-color='CCCCCC'>TOTAL</td>
					<td class="rowfoot rptdata-col-val" data-t="n" data-num-fmt="#,##0" data-fill-color='CCCCCC'><?=number_format($total_saldoawal)?></td>
					<td class="rowfoot rptdata-col-val" data-t="n" data-num-fmt="#,##0" data-fill-color='CCCCCC'><?=number_format($total_debet)?></td>
					<td class="rowfoot rptdata-col-val" data-t="n" data-num-fmt="#,##0" data-fill-color='CCCCCC'><?=number_format($total_kredit)?></td>
					<td class="rowfoot rptdata-col-val" data-t="n" data-num-fmt="#,##0" data-fill-color='CCCCCC'
					><?=number_format($total_saldoakhir)?></td>
				</tr>				
			</tbody>
			<tfoot>
			</tfoot>			
		</table>
		<script>global.totalrowcount = '<?=($i-1)?>'</script>
	</div>


</div>

<div id="wrapperfooter" class="fullwidth" style="z-index: 20">
	<div id="reportfooter" style="display: flex; justify-content: space-between; height: 10mm; ">
		&nbsp;
	<div>				
</div>