<?php

	$doc_iso_reg = "<yout form iso number>";
	$report_title['id'] = "Realisasi Budget";
	$report_title['en'] = "";

	$report_printid = strtoupper(uniqid());
	$report_printdate = date('d/m/Y');
	$report_date = $report_printdate; //$this->report_date;

	$doc_descr = "per tanggal $report_printdate";
?>



<!-- <div style="position: absolute; z-index: -100">
	<div  id="pagemeasure">&nbsp;</div>
</div> -->


<div id="wrapper" style="z-index: 10">

	<!-- page header: selalu ditampilkan pada tiap halaman, kecuali halaman 1 -->
	<div id="pageheader" class="fullwidth">
		<div>
			<div><?=$report_title['id']?></div>
			<div style="font-style: italic"><?=$doc_descr?></div>
		</div>
		<div style="text-align: right; width: 70mm;">
			<div style="display:inline-block; width: 38mm;"><b>Print Id</b> <?=$report_printid?></div>
			<div style="display:inline-block; width: 30mm;">&nbsp;</div>
			
		</div>
	</div>


	<!-- report header --->
	<div id="reporttitle" class="fullwidth">
		<div style="display: flex; justify-content: space-between">

			<div >
				<div style="font-size: 7pt; font-style: italic"><?=$doc_iso_reg?></div>
				<div style="font-weight: bold; font-size: 12pt; margin-top: 2mm"><?=$report_title['id']?></div>
				<div style="font-weight: bold; font-style: italic; font-size: 10pt; color: #666"><?=$report_title['en']?></div>
			</div>	
			<div style="text-align: right">
				<!-- <img id="ellogo" src="index.php/public/assets/logo-printform-right.svg"> -->
			</div>			
		</div>
	</div>


	<div class="fullwidth" style="position: relative; margin-top: 2mm; ">
		<div style="font-size: 8pt;">
			<b>per tanggal</b> <?=$report_date?>
		</div>
		<div style="display: flex; justify-content: space-between; margin-top: 2mm">
			<div style="font-size: 8pt;"><b>Page</b> 1 <b>of</b> <span id="reporttotalpage">1</span></div>
			<div style="text-align: right; font-size: 8pt"><b>Print Id</b> <?=$report_printid?></div>
		</div>
	</div>


	<!-- report content -->
	<div id="reportcontent" class="fullwidth">
		<table id="obj_reporttable" width="100%" data-cols-width="10,60,30">
			<thead>
				<tr>
					<th class="rowhead ptdata-col-no" data-fill-color='CCCCCC'>Li</th>
					<th class="rowhead rptdata-col-coacode" data-fill-color='CCCCCC'>ID</th>
					<th class="rowhead rptdata-col-coaname" data-fill-color='CCCCCC'>Account</th>
					<th class="rowhead rptdata-col-coaparent" data-fill-color='CCCCCC'>Budget</th>
					<th class="rowhead rptdata-col-coaparent" data-fill-color='CCCCCC'>Allocated</th>
					<th class="rowhead rptdata-col-coaparent" data-fill-color='CCCCCC'>Inquiry</th>
					<th class="rowhead rptdata-col-coaparent" data-fill-color='CCCCCC'>Realisasi</th>
				</tr>
			</thead>
			<tbody>
				<!-- 45 -->
				<?php 
				$i=0;

				$TOTAL = [
					'deptbudget_value' => 0,
					'projbudget_value' => 0,
					'inquiry_value' => 0,
					'receive_value' => 0
				];


				function add_to_total(&$TOTAL, $add) {
					foreach ($add as $key=>$value) {
						if (!array_key_exists($key, $TOTAL)) {
							$TOTAL[$key] = 0;
						}
						$TOTAL[$key] += $value;
					}
				}
				

				foreach ($this->rows as $row) { 
					$i++;

					add_to_total($TOTAL, [
						'deptbudget_value' => (float)$row['deptbudget_value'],
						'projbudget_value' => (float)$row['projbudget_value'],
						'inquiry_value' => (float)$row['inquiry_value'],
						'receive_value' => (float)$row['receive_value']
					]);

				?>
				<tr>
					<td class="row rptdata-col-no"><?=$i?></td>
					<td class="row"><?=$row['accbudget_id']?></td>
					<td class="row"><?=$row['accbudget_name']?></td>
					<td class="row"style="text-align: right"><?=number_format($row['deptbudget_value'])?></td>
					<td class="row" style="text-align: right"><?=number_format($row['projbudget_value'])?></td>
					<td class="row" style="text-align: right"><?=number_format($row['inquiry_value'])?></td>
					<td class="row" style="text-align: right"><?=number_format($row['receive_value'])?></td>
				</tr>
				<?php } ?>
				<tr>
					<td class="rowfoot" colspan="3" style="text-align: center" data-fill-color='CCCCCC'>TOTAL</td>
					<td class="rowfoot rptdata-col-val" style="text-align: right" data-t="n" data-num-fmt="#,##0" data-fill-color='CCCCCC'><?=number_format($TOTAL['deptbudget_value'])?></td>
					<td class="rowfoot rptdata-col-val" style="text-align: right" data-t="n" data-num-fmt="#,##0" data-fill-color='CCCCCC'><?=number_format($TOTAL['projbudget_value'])?></td>
					<td class="rowfoot rptdata-col-val" style="text-align: right" data-t="n" data-num-fmt="#,##0" data-fill-color='CCCCCC'><?=number_format($TOTAL['inquiry_value'])?></td>
					<td class="rowfoot rptdata-col-val" style="text-align: right" data-t="n" data-num-fmt="#,##0" data-fill-color='CCCCCC'><?=number_format($TOTAL['receive_value'])?></td>
				</tr>
			</tbody>
			<tfoot>
			</tfoot>			
		</table>
		<script>global.totalrowcount = '<?=($i-1)?>'</script>
	</div>


</div>

<div id="wrapperfooter" class="fullwidth" style="z-index: 20">
	<div id="reportfooter" style="display: flex; justify-content: space-between; height: 10mm; ">
		&nbsp;
	<div>				
</div>