<?php require_once dirname(__FILE__).'/receivable-list.phtml' ?>
<?php require_once dirname(__FILE__).'/receivable-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/receivable-debetgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/receivable-debetform.phtml' ?>
<?php require_once dirname(__FILE__).'/receivable-kreditgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/receivable-kreditform.phtml' ?>
<?php require_once dirname(__FILE__).'/receivable-referencegrid.phtml' ?>
<?php require_once dirname(__FILE__).'/receivable-referenceform.phtml' ?>
<?php require_once dirname(__FILE__).'/receivable-responsegrid.phtml' ?>
<?php require_once dirname(__FILE__).'/receivable-responseform.phtml' ?>



<div id="pnl_edit_record_custom" style="display: none">
	<div class="form_row">
		<div class="form_label_col">Commit By</div>
		<div class="form_input_col" style="border: 0px solid black">
			<span id="pnl_edit_record-commitby"></span>
		</div>
	</div>	

	<div class="form_row">
		<div class="form_label_col">Commit Date</div>
		<div class="form_input_col" style="border: 0px solid black">
			<span id="pnl_edit_record-commitdate"></span>
		</div>
	</div> 
</div>		
		
