<div id="pnl_list">
	<!-- <div class="fgta-page-title">Trial Balance</div> -->

	<div id="pnl_list-pnl_head" style="display: flex; justify-content: space-between; margin-top: 10px; align-items: flex-end">
	<!--<div>-->
		<!--<span>Budget</span>-->
		<!--<input id="pnl_list-dt_report_date" class="easyui-datebox" style="width: 130px" mapping="jurnal_date" data-options="editable:false ">-->
		<!--<input id="pnl_list-cbo_corpbudget_id" class="easyui-combo" style="width: 100%">-->
		<!--<span>Type Report</span>-->
		<!--<input id="pnl_list-dt_report_date" class="easyui-datebox" style="width: 130px" mapping="jurnal_date" data-options="editable:false ">-->
		<!--<input id="pnl_list-cbo_reporttype" class="easyui-combo" style="width: 100%">-->
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-param" style="width: 280px">
				<div class="list-search-item" style="width: 50px;align-self:center;">Budget</div>
				<div class="list-search-item" style="width: 200px">
					<input id="pnl_list-cbo_corpbudget_id" class="easyui-combo" style="width: 100%">
				</div>
			</div>


			<input id="pnl_list-cbo_reporttype_id" class="easyui-combo" style="width: 100%">
			<div class="list-search-param" style="width: 280px">
				<div class="list-search-item" style="width: 50px; align-self:center; text-align: right">Type Report</div>
				<div class="list-search-item" style="width: 200px">
					
				</div>
			</div>

			<div class="list-search-item" style="width: 45px">
			<a href="javascript:void(0)" id="pnl_list-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>
		</div>		

		<div class="list-search-wrap"  style="display: flex;">
			<a href="javascript:void(0)" id="pnl_list-btn_export" class="easyui-linkbutton c8" style="width: 100px">Export</a>
			&nbsp;
			<a href="javascript:void(0)" id="pnl_list-btn_print" class="easyui-linkbutton c8" style="width: 45px">Print</a>
		</div>
	</div>			
	<div id="rpt_container"  style="margin-top: 10px; border: 1px solid #000">
		<iframe id="obj_report" style="border: 0px; width:100%; height:100%;">
		</iframe>
	</div>
</div>	