<div id="pnl_editdetilform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Detil</div>
		<a id="pnl_editdetilform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_editdetilform-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>


	<form id="pnl_editdetilform-form">

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetilform-txt_deptbudgetdet_id" class="easyui-textbox" mapping="deptbudgetdet_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Account</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetilform-cbo_accbudget_id" class="easyui-combo" style="width: 400px" mapping="accbudget_id" display="accbudget_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Account Budget harus diisi', prompt: '-- PILIH --'"  validType="requiredcombo['pnl_editdetilform-cbo_accbudget_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Descr</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetilform-txt_deptbudgetdet_descr" class="easyui-textbox" mapping="deptbudgetdet_descr"  maxlength="255"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">JAN</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetilform-txt_deptbudgetdet_01" class="easyui-numberbox" mapping="deptbudgetdet_01" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , required: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">FEB</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetilform-txt_deptbudgetdet_02" class="easyui-numberbox" mapping="deptbudgetdet_02" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , required: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">MAR</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetilform-txt_deptbudgetdet_03" class="easyui-numberbox" mapping="deptbudgetdet_03" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , required: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">APR</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetilform-txt_deptbudgetdet_04" class="easyui-numberbox" mapping="deptbudgetdet_04" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , required: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">MEI</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetilform-txt_deptbudgetdet_05" class="easyui-numberbox" mapping="deptbudgetdet_05" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , required: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">JUN</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetilform-txt_deptbudgetdet_06" class="easyui-numberbox" mapping="deptbudgetdet_06" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , required: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">JUL</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetilform-txt_deptbudgetdet_07" class="easyui-numberbox" mapping="deptbudgetdet_07" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , required: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">AGS</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetilform-txt_deptbudgetdet_08" class="easyui-numberbox" mapping="deptbudgetdet_08" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , required: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">SEP</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetilform-txt_deptbudgetdet_09" class="easyui-numberbox" mapping="deptbudgetdet_09" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , required: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">OKT</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetilform-txt_deptbudgetdet_10" class="easyui-numberbox" mapping="deptbudgetdet_10" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , required: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">NOV</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetilform-txt_deptbudgetdet_11" class="easyui-numberbox" mapping="deptbudgetdet_11" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , required: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">DES</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetilform-txt_deptbudgetdet_12" class="easyui-numberbox" mapping="deptbudgetdet_12" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , required: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Total</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetilform-txt_deptbudgetdet_total" class="easyui-numberbox" mapping="deptbudgetdet_total" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:',', disabled: true  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>


		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Coa</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetilform-txt_coa_id" class="easyui-textbox" mapping="coa_id"  maxlength="255"  style="width: 400px" data-options="multiline:false, disabled: true  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Coa Report</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetilform-txt_coareport_id" class="easyui-textbox" mapping="coareport_id"  maxlength="255"  style="width: 400px" data-options="multiline:false, disabled: true  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Notes</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetilform-txt_deptbudgetdet_notes" class="easyui-textbox" mapping="deptbudgetdet_notes"  maxlength="255"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">BudgetID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetilform-txt_deptbudget_id" class="easyui-textbox" mapping="deptbudget_id"  maxlength="35"  style="width: 400px" data-options="multiline:false  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_editdetilform-autoadd" type="checkbox"><label for="pnl_editdetilform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_editdetilform-btn_save" class="easyui-linkbutton c1" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	



	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div>
			<a id="pnl_editdetilform-btn_prev" class="easyui-linkbutton c8" style="width: 50px">Prev</a>
			<a id="pnl_editdetilform-btn_next" class="easyui-linkbutton c8" style="width: 50px">Next</a>
		</div>

		<div>
			<a id="pnl_editdetilform-btn_addnew" class="easyui-linkbutton c8" style="width: 100px">Tambah Baru</a>
		</div>

		<div>
			<a id="pnl_editdetilform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>




</div>	
