<div id="pnl_list">
	<div class="fgta-page-title">Daftar Partner</div>

	<div id="pnl_list-pnl_head" style="display: flex; align-items: flex-end">
		<!-- Simple Query -->
		<div class="list-buttonbaru" style="text-align: right; width: calc(100% - 10px); float: right;  position: absolute">
			<a href="javascript:void(0)" id="pnl_list-btn_new" class="easyui-linkbutton c8" style="width: 60px">Baru</a>
		</div>

		<!-- START: Query Box -->
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-param" style="width: 230px">
				<div class="list-search-item" style="width: 50px; align-self:center; text-align: right">Type</div>
				<div class="list-search-item" style="width: 150px">
					<input id="pnl_list-cbo_search_type" class="easyui-combo" style="width: 100%">
				</div>
			</div>

			<div class="list-search-param" style="width: 180px">
				<div class="list-search-item" style="width: 25px; align-self:center; text-align: right">Cari</div>
				<div class="list-search-item" style="width: 150px">
					<input id="pnl_list-txt_search" class="easyui-textbox" style="width: 100%">
				</div>
			</div>
			
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_list-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>
		</div>
		<!-- END: Query Box -->


	</div>


	<div style="margin-top: 10px">
		<table id="pnl_list-tbl_list" paging="true" cellspacing="0" width="100%" class="deftable">
			<thead>
				<tr>
					<th mapping="partner_id">partner_id</th>
					<th mapping="partner_name">partner_name</th>
					<th mapping="partner_isdisabled" type="checkbox">partner_isdisabled</th>
					<th mapping="partnertype_name">partnertype_name</th>

				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Name</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Disabled</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Type</td>

				</tr>
			</thead>
		</table>
	</div>



</div>