<?php require_once dirname(__FILE__).'/partner-list.phtml' ?>
<?php require_once dirname(__FILE__).'/partner-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/partner-bankgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/partner-bankform.phtml' ?>
<?php require_once dirname(__FILE__).'/partner-contactgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/partner-contactform.phtml' ?>
<?php require_once dirname(__FILE__).'/partner-sitegrid.phtml' ?>
<?php require_once dirname(__FILE__).'/partner-siteform.phtml' ?>
<?php require_once dirname(__FILE__).'/partner-modeltransaksigrid.phtml' ?>
<?php require_once dirname(__FILE__).'/partner-modeltransaksiform.phtml' ?>
<?php require_once dirname(__FILE__).'/partner-refgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/partner-refform.phtml' ?>



