<?php require_once dirname(__FILE__).'/jurnallink-list.phtml' ?>
<?php require_once dirname(__FILE__).'/jurnallink-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/jurnallink-detilgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/jurnallink-detilform.phtml' ?>
<?php require_once dirname(__FILE__).'/jurnallink-referencegrid.phtml' ?>
<?php require_once dirname(__FILE__).'/jurnallink-referenceform.phtml' ?>
<?php require_once dirname(__FILE__).'/jurnallink-responsegrid.phtml' ?>
<?php require_once dirname(__FILE__).'/jurnallink-responseform.phtml' ?>



