<div id="pnl_list">
	<div class="fgta-page-title">Daftar Cash Discount</div>

	<div id="pnl_list-pnl_head" style="display: flex; align-items: flex-end">
		<!-- Simple Query -->
		<div class="list-buttonbaru" style="text-align: right; width: calc(100% - 10px); float: right;  position: absolute">
			<a href="javascript:void(0)" id="pnl_list-btn_new" class="easyui-linkbutton c8" style="width: 60px">Baru</a>
		</div>
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-item" style="width: 50px;">Cari</div>
			<div class="list-search-item">
				<input id="pnl_list-txt_search" class="easyui-textbox" style="width: 100%">
			</div>
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_list-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>
		</div>
	</div>


	<div style="margin-top: 10px">
		<table id="pnl_list-tbl_list" paging="true" cellspacing="0" width="100%" class="deftable">
			<thead>
				<tr>
					<th mapping="cashdiscount_id">cashdiscount_id</th>
					<th mapping="partner_name">partner_name</th>
					<th mapping="cashdiscount_date">cashdiscount_date</th>
					<th mapping="cashdiscount_descr">cashdiscount_descr</th>
					<th mapping="cashdiscount_percent" style="text-align: right"  formatter="row_format_number">cashdiscount_percent</th>
					<th mapping="cashdiscount_validr" style="text-align: right"  formatter="row_format_number">cashdiscount_validr</th>
					<th mapping="doc_name">doc_name</th>
					<th mapping="cashdiscount_iscommit" type="checkbox">cashdiscount_iscommit</th>
					<th mapping="cashdiscount_isapprovalprogress" type="checkbox">cashdiscount_isapprovalprogress</th>
					<th mapping="cashdiscount_isapproved" type="checkbox">cashdiscount_isapproved</th>
					<th mapping="cashdiscount_isdeclined" type="checkbox">cashdiscount_isdeclined</th>

				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Partner</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Date</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Description</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">IDR</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">IDR</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Order Doc</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Commit</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Progress</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Approved</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Declined</td>

				</tr>
			</thead>
		</table>
	</div>



</div>