<div id="pnl_edittargetgrid">
	<div class="fgta-page-title">Daftar Target</div>
	<div id="pnl_edittargetgrid-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>

	<!--// Untuk keperluan search di detil
	<div id="pnl_edittargetgrid-pnl_head" style="display: flex; align-items: flex-end">
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-item" style="width: 50px;">Cari</div>
			<div class="list-search-item">
				<input id="pnl_edittargetgrid-txt_search" class="easyui-textbox" style="width: 100%">
			</div>
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_edittargetgrid-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>
		</div>
	</div>	
	//-->

	<div style="margin-top: 10px; margin-bottom: 15px">
		<table id="pnl_edittargetgrid-tbl_list" paging="true" cellspacing="0" width="100%" class="deftable">
			<thead>
				<tr>
					<th mapping="colltarprddetil_descr">colltarprddetil_descr</th>
					<th mapping="colltarprddetil_valpartnerost" style="text-align: right" formatter="row_format_number">colltarprddetil_valpartnerost</th>
					<th mapping="colltarprddetil_valpartner" style="text-align: right" formatter="row_format_number">colltarprddetil_valpartner</th>
					<th mapping="colltarprddetil_val" style="text-align: right" formatter="row_format_number">colltarprddetil_val</th>
				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="border-bottom: 1px solid #000000">Descr</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Outstanding Value</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Adjusted Value</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Value</td>

				</tr>
			</thead>
		</table>
	</div>

	<div id="pnl_edittargetgrid-control" style="display: flex; justify-content: space-between; margin-bottom: 100px">
		<div>
			<span style="display:none">
				<a id="pnl_edittargetgrid-removechecked" href="javascript:void(0)" class="easyui-linkbutton c8">Hapus Checked</a>
			</span>
		</div>

		<div>
			<span style="display:none">
				<a id="pnl_edittargetgrid-addrow" href="javascript:void(0)" class="easyui-linkbutton c8">Tambah Baris</a>
			</span>	
			<a id="pnl_edittargetgrid-getdata" href="javascript:void(0)" class="easyui-linkbutton c8">Get Data</a>
		</div>

		<div>
		</div>

	</div>


</div>	
