<?php require_once dirname(__FILE__).'/colltarprd-list.phtml' ?>
<?php require_once dirname(__FILE__).'/colltarprd-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/colltarprd-partnerexcgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/colltarprd-partnerexcform.phtml' ?>
<?php require_once dirname(__FILE__).'/colltarprd-targetgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/colltarprd-targetform.phtml' ?>



